### ISSUE TITLE
Can't reorder/nest Menu Items from Customizer

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/customify#242]
Ref https://github.com/pixelgrade/style-manager/issues/6

LE: At first I thought that in Customify we are encountering the same problem, however it looks like you can nest menu items, but the style is broken in some cases:
![Customify-Menu-Section](https://user-images.githubusercontent.com/46342490/128033687-055f16b6-9d9d-4c16-80d4-7f61d646eca2.png)

**Comment by georgeolaru** [comment]
## Investigation

This is a CSS conflict where Customify's Customizer styles interfere with the WordPress menu section's drag-and-drop nesting UI.

### Problematic CSS

Two locations apply styles that affect menu items in the Customizer:

1. **`scss/_shame.scss` (lines 7-13):**
```scss
#accordion-section-add_menu {
    border-bottom: none;
    .add-menu-toggle {
        float: none;
    }
}
```

2. **`scss/_customize-control.scss` (lines 102-107):**
```scss
&.menu-item {
    .menu-item-settings {
        width: 100%;
        background-color: $blue-white;
    }
}
```

The `width: 100%` on `.menu-item-settings` and the `float: none` on `.add-menu-toggle` can break the positioning and indentation calculations that WordPress relies on for menu nesting visual feedback.

### Recommended fix

- Scope the `.menu-item` styles more carefully, or remove the `width: 100%` override which conflicts with WordPress core's menu nesting indentation
- Test with WordPress's native Customizer menu section to ensure drag handles and nesting indicators work correctly after the CSS change
- The `_shame.scss` file name suggests these were known workarounds — they may need to be revisited for newer WordPress versions
